"""
Phase 1 — Analytical Theory and Steady-State Analysis
======================================================

Goals:
  1. Derive and map the steady-state pointer-state separation |Δα_ss| vs χ/κ.
    2. Show the optimal drive frequency is ω_d = ω_r + χ/2, equivalently Δ_g = −χ/2.
  3. Compute SNR² vs κT in steady-state and compare against time-resolved simulation.
  4. Validate analytical results against cqed_sim.ReadoutResonator (cross-check).
  5. Compare endpoint-separation and integrated-SNR² objectives to motivate Phase 2.
  6. Quantify the steady-state photon number and measurement rate γ_meas.

Outputs:
  data/phase1_results.npz  — all numerical arrays
  (figures generated by plot_results.py)
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

import numpy as np
from common import (
    TWO_PI, KAPPA, CHI_NOMINAL, OMEGA_R, EPSILON_MAX, G_COUP,
    CHI_KAPPA_VALUES, CHI_VALUES, KAPPA_T_VALUES, T_READ_VALUES,
    DT_ODE, EPSILON_MAX,
    steady_state_alpha, optimal_delta_g, steady_state_separation,
    max_steady_state_separation, optimal_separation_formula,
    simulate_conditioned_fields, snr_squared, endpoint_separation_sq,
    assignment_fidelity_from_snr2, residual_photons,
    make_readout_resonator, cqed_sim_steady_state,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
os.makedirs(DATA_DIR, exist_ok=True)


def study_optimal_drive_frequency(
    kappa: float, chi: float, epsilon: float, n_grid: int = 300
) -> dict:
    """
    Sweep drive detuning Δ_g over [−2|χ|, +|χ|] and compute |Δα^ss|,
    SNR rate γ_meas, and photon numbers n_g, n_e.

    Returns arrays for plotting.
    """
    delta_g_values = np.linspace(-2.0 * abs(chi), abs(chi), n_grid)
    sep = np.array([
        steady_state_separation(epsilon, kappa, chi, dg) for dg in delta_g_values
    ])
    n_g = np.array([
        abs(steady_state_alpha(epsilon, kappa, dg)) ** 2 for dg in delta_g_values
    ])
    n_e = np.array([
        abs(steady_state_alpha(epsilon, kappa, dg + chi)) ** 2 for dg in delta_g_values
    ])
    gamma_meas = 0.5 * kappa * sep ** 2

    return {
        "delta_g_values": delta_g_values,
        "sep": sep,
        "n_g": n_g,
        "n_e": n_e,
        "gamma_meas": gamma_meas,
    }


def steady_state_separation_vs_chi_kappa(
    kappa: float, epsilon: float
) -> dict:
    """
    Compute analytical |Δα^ss_max|, n_g+n_e, and γ_meas at optimal Δ_g,
    as a function of χ/κ.
    """
    chi_kappa_scan = np.linspace(0.05, 6.0, 400)
    chi_scan = chi_kappa_scan * kappa

    sep_analytical = np.array([
        optimal_separation_formula(epsilon, kappa, chi) for chi in chi_scan
    ])
    n_g_ss = np.array([
        abs(steady_state_alpha(epsilon, kappa, optimal_delta_g(chi))) ** 2
        for chi in chi_scan
    ])
    n_e_ss = np.array([
        abs(steady_state_alpha(epsilon, kappa, optimal_delta_g(chi) + chi)) ** 2
        for chi in chi_scan
    ])
    gamma_meas = 0.5 * kappa * sep_analytical ** 2

    return {
        "chi_kappa_scan": chi_kappa_scan,
        "sep_max_analytical": sep_analytical,
        "n_g_ss": n_g_ss,
        "n_e_ss": n_e_ss,
        "gamma_meas": gamma_meas,
    }


def snr_vs_kappa_t(
    kappa: float, chi: float, epsilon: float, dt: float = DT_ODE
) -> dict:
    """
    Compute SNR² and endpoint separation vs κT for:
    (a) analytical steady-state approximation: SNR² ≈ κT · |Δα^ss|²
    (b) exact ODE integration with square pulse at optimal Δ_g.

    Also compare drive-on-resonance vs drive-at-midpoint.
    """
    kappa_t_scan = np.linspace(0.2, 25.0, 120)
    T_scan = kappa_t_scan / kappa
    delta_g_opt = optimal_delta_g(chi)
    delta_g_res = 0.0     # drive on resonance with |g⟩

    snr2_ss_approx = np.zeros(len(T_scan))      # steady-state approx
    snr2_ode_opt   = np.zeros(len(T_scan))      # ODE, midpoint drive
    snr2_ode_res   = np.zeros(len(T_scan))      # ODE, on-resonance drive
    endsep_ode_opt = np.zeros(len(T_scan))
    endsep_ode_res = np.zeros(len(T_scan))

    sep_ss_opt = max_steady_state_separation(epsilon, kappa, chi)
    sep_ss_res = steady_state_separation(epsilon, kappa, chi, 0.0)

    for i, (T, kT) in enumerate(zip(T_scan, kappa_t_scan)):
        N = max(2, int(round(T / dt)))
        tlist = np.linspace(0.0, T, N + 1)
        eps_arr = epsilon * np.ones(N, dtype=np.complex128)

        # Midpoint drive
        ag, ae = simulate_conditioned_fields(eps_arr, tlist, kappa, chi, delta_g_opt)
        snr2_ode_opt[i] = snr_squared(ag, ae, tlist, kappa)
        endsep_ode_opt[i] = endpoint_separation_sq(ag, ae)

        # On-resonance drive
        ag_r, ae_r = simulate_conditioned_fields(eps_arr, tlist, kappa, chi, delta_g_res)
        snr2_ode_res[i] = snr_squared(ag_r, ae_r, tlist, kappa)
        endsep_ode_res[i] = endpoint_separation_sq(ag_r, ae_r)

        # Steady-state approximation (only valid for κT >> 1)
        snr2_ss_approx[i] = kappa * T * sep_ss_opt ** 2

    return {
        "kappa_t_scan": kappa_t_scan,
        "snr2_ss_approx": snr2_ss_approx,
        "snr2_ode_opt": snr2_ode_opt,
        "snr2_ode_res": snr2_ode_res,
        "endsep_ode_opt": endsep_ode_opt,
        "endsep_ode_res": endsep_ode_res,
        "F_assign_ode_opt": np.array([assignment_fidelity_from_snr2(s) for s in snr2_ode_opt]),
        "F_assign_ode_res": np.array([assignment_fidelity_from_snr2(s) for s in snr2_ode_res]),
    }


def cqed_sim_validation(kappa: float, chi: float, epsilon: float) -> dict:
    """
    Cross-validate analytical steady-state against cqed_sim.ReadoutResonator.

    Checks |Δα^ss_analytical| ≈ |Δα^ss_cqed_sim| for both resonance and midpoint drives.
    """
    results = {}
    for label, delta_g in [("resonance", 0.0), ("midpoint", optimal_delta_g(chi))]:
        # Analytical
        ag_an = steady_state_alpha(epsilon, kappa, delta_g)
        ae_an = steady_state_alpha(epsilon, kappa, delta_g + chi)
        sep_an = abs(ae_an - ag_an)

        # cqed_sim
        ag_cs, ae_cs = cqed_sim_steady_state(kappa, chi, epsilon, delta_g)
        sep_cs = abs(ae_cs - ag_cs)

        err = abs(sep_an - sep_cs) / max(sep_an, 1e-30)
        results[label] = {
            "alpha_g_analytical": ag_an,
            "alpha_e_analytical": ae_an,
            "alpha_g_cqed_sim": ag_cs,
            "alpha_e_cqed_sim": ae_cs,
            "sep_analytical": sep_an,
            "sep_cqed_sim": sep_cs,
            "relative_error": err,
        }
    return results


def objective_comparison(
    kappa: float, chi: float, epsilon: float, dt: float = DT_ODE
) -> dict:
    """
    Compare endpoint separation vs integrated SNR² as readout metrics.

    Varying κT, show how endpoint separation saturates earlier than SNR² and
    that they agree only in steady-state regime (κT >> 1).
    """
    kappa_t_scan = np.linspace(0.1, 20.0, 100)
    T_scan = kappa_t_scan / kappa
    delta_g_opt = optimal_delta_g(chi)

    snr2_arr = np.zeros(len(T_scan))
    endsep_arr = np.zeros(len(T_scan))
    # Integrated distinguishability normalized by κT |Δα_ss|²
    # (ratio of achieved to maximum-extrapolated SNR)
    snr2_ss_arr = np.zeros(len(T_scan))

    sep_ss = max_steady_state_separation(epsilon, kappa, chi)

    for i, (T, kT) in enumerate(zip(T_scan, kappa_t_scan)):
        N = max(2, int(round(T / dt)))
        tlist = np.linspace(0.0, T, N + 1)
        eps_arr = epsilon * np.ones(N, dtype=np.complex128)
        ag, ae = simulate_conditioned_fields(eps_arr, tlist, kappa, chi, delta_g_opt)
        snr2_arr[i] = snr_squared(ag, ae, tlist, kappa)
        endsep_arr[i] = endpoint_separation_sq(ag, ae)
        snr2_ss_arr[i] = kappa * T * sep_ss ** 2

    # Efficiency = SNR² / SNR²_ss_approx (saturates at 1 for large κT)
    efficiency = snr2_arr / np.maximum(snr2_ss_arr, 1e-30)

    return {
        "kappa_t_scan": kappa_t_scan,
        "snr2_arr": snr2_arr,
        "endsep_arr": endsep_arr,
        "snr2_ss_approx": snr2_ss_arr,
        "efficiency": efficiency,
        "endsep_ss": sep_ss ** 2,
    }


def main() -> None:
    print("=" * 60)
    print("Phase 1: Analytical Theory and Steady-State Analysis")
    print("=" * 60)

    kappa   = KAPPA
    chi     = CHI_NOMINAL      # χ/κ = 1 at nominal
    epsilon = EPSILON_MAX * 0.6   # moderate drive (≈3 ss photons)

    # ── 1. Optimal drive frequency study ────────────────────────────────────
    print("\n[1/5] Sweeping drive detuning for optimal readout frequency...")
    drive_freq_data = study_optimal_drive_frequency(kappa, chi, epsilon)
    dg_opt = optimal_delta_g(chi)
    sep_max = max_steady_state_separation(epsilon, kappa, chi)
    sep_formula = optimal_separation_formula(epsilon, kappa, chi)
    idx_max = np.argmax(drive_freq_data["sep"])
    print(f"  Optimal Δ_g/2π = {drive_freq_data['delta_g_values'][idx_max]/TWO_PI*1e-6:.3f} MHz")
    print(f"  Analytical Δ_g_opt/2π = {dg_opt/TWO_PI*1e-6:.3f} MHz")
    print(f"  |Δα_ss_max| (formula) = {sep_formula:.4f}")
    print(f"  |Δα_ss_max| (sweep)   = {drive_freq_data['sep'][idx_max]:.4f}")

    # ── 2. Separation vs χ/κ ────────────────────────────────────────────────
    print("\n[2/5] Computing |Δα_ss_max| vs χ/κ...")
    chi_kappa_data = steady_state_separation_vs_chi_kappa(kappa, epsilon)
    idx_ck_1 = np.argmin(np.abs(chi_kappa_data["chi_kappa_scan"] - 1.0))
    print(f"  At χ/κ=1: |Δα_ss_max| = {chi_kappa_data['sep_max_analytical'][idx_ck_1]:.4f}")
    print(f"  Peak at χ/κ = {chi_kappa_data['chi_kappa_scan'][np.argmax(chi_kappa_data['sep_max_analytical'])]:.2f}")
    print(f"  (analytical maximum at χ/κ = 1 → |Δα_ss_max| = 2|ε|/κ)")

    # ── 3. SNR vs κT ────────────────────────────────────────────────────────
    print("\n[3/5] Computing SNR² and endpoint separation vs κT...")
    snr_kT_data = snr_vs_kappa_t(kappa, chi, epsilon)
    idx_kT5 = np.argmin(np.abs(snr_kT_data["kappa_t_scan"] - 5.0))
    print(f"  κT=5: SNR²_ode_opt={snr_kT_data['snr2_ode_opt'][idx_kT5]:.3f}, "
          f"F_assign={snr_kT_data['F_assign_ode_opt'][idx_kT5]:.4f}")
    print(f"  κT=5: SNR²_ode_res={snr_kT_data['snr2_ode_res'][idx_kT5]:.3f}")
    print(f"  Midpoint drive advantage: "
          f"{snr_kT_data['snr2_ode_opt'][idx_kT5]/snr_kT_data['snr2_ode_res'][idx_kT5]:.3f}x")

    # ── 4. cqed_sim validation ───────────────────────────────────────────────
    print("\n[4/5] Validating against cqed_sim.ReadoutResonator...")
    val = cqed_sim_validation(kappa, chi, epsilon)
    for label, res in val.items():
        print(f"  Drive at {label}:")
        print(f"    Analytical |Δα| = {res['sep_analytical']:.6f}")
        print(f"    cqed_sim   |Δα| = {res['sep_cqed_sim']:.6f}")
        print(f"    Relative error  = {res['relative_error']:.2e}")

    # ── 5. Objective comparison ──────────────────────────────────────────────
    print("\n[5/5] Comparing endpoint vs integrated-SNR² objectives...")
    obj_comp = objective_comparison(kappa, chi, epsilon)
    idx_kT3 = np.argmin(np.abs(obj_comp["kappa_t_scan"] - 3.0))
    print(f"  κT=3: SNR² efficiency = {obj_comp['efficiency'][idx_kT3]:.3f} "
          f"(fraction of steady-state extrapolation)")
    print(f"  κT=3: endpoint sep = {obj_comp['endsep_arr'][idx_kT3]:.4f}")
    print(f"  κT=3: |Δα_ss|²     = {obj_comp['endsep_ss']:.4f}")

    # ── Save results ─────────────────────────────────────────────────────────
    outpath = os.path.join(DATA_DIR, "phase1_results.npz")
    np.savez(
        outpath,
        # Drive frequency sweep
        **{f"drive_freq_{k}": v for k, v in drive_freq_data.items()},
        # Separation vs chi/kappa
        **{f"chi_kappa_{k}": v for k, v in chi_kappa_data.items()},
        # SNR vs kT
        **{f"snr_kT_{k}": v for k, v in snr_kT_data.items()},
        # Objective comparison
        **{f"obj_cmp_{k}": v for k, v in obj_comp.items()},
        # Scalars
        kappa=kappa, chi=chi, epsilon=epsilon,
        delta_g_opt=optimal_delta_g(chi),
        sep_max=sep_max,
        # Validation errors
        cqed_sim_error_resonance=val["resonance"]["relative_error"],
        cqed_sim_error_midpoint=val["midpoint"]["relative_error"],
    )
    print(f"\nResults saved to {outpath}")

    # ── Summary print ────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Phase 1 Summary:")
    print(f"  Optimal drive: ω_d = ω_r + χ/2  (Δ_g = −χ/2 = {dg_opt/TWO_PI*1e-6:.2f} MHz)")
    print(f"  Max |Δα_ss|: {sep_max:.4f}  at χ/κ=1")
    print(f"  cqed_sim max validation error: "
          f"{max(val['resonance']['relative_error'], val['midpoint']['relative_error']):.2e}")
    print(f"  Integrated SNR² is the more informative objective (endpoint lags)")
    print("=" * 60)


if __name__ == "__main__":
    main()
