"""Build the reproducibility notebook for the gf-sideband waveform study."""

from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
STUDY_DIR = SCRIPT_DIR.parent
NOTEBOOK_PATH = SCRIPT_DIR / "reproducibility_notebook.ipynb"


def markdown_cell(source: str) -> dict[str, object]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line if line.endswith("\n") else line + "\n" for line in source.splitlines()],
    }


def code_cell(source: str) -> dict[str, object]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line if line.endswith("\n") else line + "\n" for line in source.splitlines()],
    }


def build_notebook() -> dict[str, object]:
    study_root = str(STUDY_DIR).replace("\\", "/")
    script_root = str(SCRIPT_DIR).replace("\\", "/")
    cells = [
        markdown_cell(
            """# Reproducibility Notebook

    This notebook reproduces the saved outputs for the `|f,n-1> <-> |g,n>` sideband waveform-optimization study, including the simultaneous two-tone storage-to-readout transfer extension. The default path loads the saved machine-readable artifacts and figures generated by the main sweep so the notebook stays lightweight and rerunnable on a normal workstation."""
        ),
        markdown_cell(
            """## Environment Setup

This cell imports the standard library helpers needed to load the saved study outputs and display the key figures."""
        ),
        code_cell(
            f"""from __future__ import annotations

import csv
import json
from pathlib import Path
from pprint import pprint

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

STUDY_DIR = Path(r"{study_root}")
SCRIPT_DIR = Path(r"{script_root}")
DATA_DIR = STUDY_DIR / "data"
FIGURES_DIR = STUDY_DIR / "figures"
ARTIFACTS_DIR = STUDY_DIR / "artifacts"


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def show_image(path: Path, title: str) -> None:
    image = mpimg.imread(path)
    plt.figure(figsize=(9, 5))
    plt.imshow(image)
    plt.axis("off")
    plt.title(title)
    plt.show()
"""
        ),
        markdown_cell(
            """## User-Tunable Parameters

    All notebook knobs live in the next cell. The default behavior is to load saved results only. Setting `rerun_main_study` to `True` reruns the full waveform study, while `rerun_two_tone_extension` reruns only the simultaneous-transfer extension."""
        ),
        code_cell(
            """# User-tunable parameters for notebook replay
selected_mode = "storage"
selected_criterion = "selective"
selected_n = 1
rerun_main_study = False
    rerun_two_tone_extension = False
rerun_validation = False

print("selected_mode =", selected_mode)
print("selected_criterion =", selected_criterion)
print("selected_n =", selected_n)
print("rerun_main_study =", rerun_main_study)
    print("rerun_two_tone_extension =", rerun_two_tone_extension)
print("rerun_validation =", rerun_validation)
"""
        ),
        markdown_cell(
            """## Derived Objects

This cell loads all saved tables and JSON artifacts used throughout the notebook. Re-running the parameter cell above and then this cell is enough to update the selection variables used later in the notebook."""
        ),
        code_cell(
            """study_results = json.loads((DATA_DIR / "study_results.json").read_text(encoding="utf-8"))
device_parameter_rows = read_csv_rows(DATA_DIR / "device_parameter_table.csv")
noise_scenarios = read_csv_rows(DATA_DIR / "noise_scenarios.csv")
winner_rows = read_csv_rows(DATA_DIR / "winner_table.csv")
gate_winner_rows = read_csv_rows(DATA_DIR / "gate_winner_table.csv")
refined_rows = read_csv_rows(DATA_DIR / "refined_cases.csv")
open_system_rows = read_csv_rows(DATA_DIR / "open_system_followup.csv")
open_system_summary_rows = read_csv_rows(DATA_DIR / "open_system_summary.csv")
open_system_transmon_winner_rows = read_csv_rows(DATA_DIR / "open_system_transmon_reference_winner_table.csv")
validation_frequency_rows = read_csv_rows(DATA_DIR / "validation_frequency.csv")
validation_convergence_rows = read_csv_rows(DATA_DIR / "validation_convergence.csv")
two_tone_results = json.loads((DATA_DIR / "two_tone_results.json").read_text(encoding="utf-8"))
two_tone_selected_rows = read_csv_rows(DATA_DIR / "two_tone_selected_cases.csv")
two_tone_open_system_rows = read_csv_rows(DATA_DIR / "two_tone_open_system.csv")
two_tone_validation_frequency_rows = read_csv_rows(DATA_DIR / "validation_two_tone_frequency.csv")
two_tone_validation_convergence_rows = read_csv_rows(DATA_DIR / "validation_two_tone_convergence.csv")

selected_refined = [
    row
    for row in refined_rows
    if row["mode"] == selected_mode
    and row["criterion"] == selected_criterion
    and int(row["n"]) == selected_n
]

print("Loaded winner rows:", len(winner_rows))
print("Loaded gate-winner rows:", len(gate_winner_rows))
print("Loaded refined rows:", len(refined_rows))
print("Selected refined rows:", len(selected_refined))
print("Loaded two-tone selected rows:", len(two_tone_selected_rows))
"""
        ),
        markdown_cell(
            """## Step-by-Step Reproduction

This section first loads the saved winner summaries and then provides commented-out cells that can rerun the study scripts if a full recomputation is desired."""
        ),
        code_cell(
            """# --- Load saved results (default) ---
pprint(winner_rows)
print("\\nGate-oriented summary:")

selected_two_tone = [
    row
    for row in two_tone_selected_rows
    if int(row["n"]) == selected_n
]
print("\nTwo-tone selected cases for n=", selected_n)
pprint(selected_two_tone)
pprint(gate_winner_rows)

if selected_refined:
    print("\\nSelected refined case:")
    pprint(selected_refined[0])
"""
        ),
        code_cell(
# if rerun_two_tone_extension:
#     subprocess.run([sys.executable, str(SCRIPT_DIR / "two_tone_transfer_extension.py")], check=True)
            """# --- Re-run with current parameters ---
# import subprocess
# import sys
# if rerun_main_study:
#     subprocess.run([sys.executable, str(SCRIPT_DIR / "run_study.py")], check=True)
# if rerun_validation:
#     subprocess.run([sys.executable, str(SCRIPT_DIR / "validate_results.py")], check=True)
"""
        ),
        markdown_cell(
            """## Validation

This cell reproduces the saved sanity-check and convergence summaries."""
        ),
        code_cell(
            """print("Frequency validation:")
pprint(validation_frequency_rows)

print("\\nConvergence validation:")
pprint(validation_convergence_rows)

    print("\nTwo-tone frequency validation:")
    pprint(two_tone_validation_frequency_rows)

    print("\nTwo-tone convergence validation:")
    pprint(two_tone_validation_convergence_rows)
"""
        ),
        markdown_cell(
            """## Key Figures

These cells display the core figures from the saved study output."""
        ),
        code_cell(
            """print("Device parameter provenance:")
pprint(device_parameter_rows)

print("\\nNoise scenarios:")
pprint(noise_scenarios)

print("\\nOpen-system summary:")
pprint(open_system_summary_rows)

print("\\nThreshold-valid winners after transmon-reference reranking:")
pprint(open_system_transmon_winner_rows)

print("\nTwo-tone open-system summary:")
pprint(two_tone_open_system_rows)
"""
        ),
        code_cell(
            """show_image(FIGURES_DIR / "sideband_frequency_map.png", "Sideband frequency map")
show_image(FIGURES_DIR / "duration_tradeoff_n1.png", "Duration tradeoff at n=1")
show_image(FIGURES_DIR / "winner_frontier.png", "Winner frontier")
"""
        ),
        code_cell(
            """show_image(FIGURES_DIR / "population_dynamics_representative.png", "Representative dynamics")
show_image(FIGURES_DIR / "robustness_maps.png", "Robustness maps")
show_image(FIGURES_DIR / "spectral_intuition.png", "Spectral intuition")
show_image(FIGURES_DIR / "open_system_scenario_summary.png", "Open-system scenario summary")
show_image(FIGURES_DIR / "two_tone_scan_summary.png", "Two-tone simultaneous-transfer scan summary")
show_image(FIGURES_DIR / "two_tone_population_dynamics.png", "Two-tone population dynamics")
show_image(FIGURES_DIR / "two_tone_open_system_summary.png", "Two-tone open-system summary")
"""
        ),
        markdown_cell(
            """## Summary

The saved study outputs support three main conclusions.

1. A wide Gaussian envelope is the best closed-system selective family for both sideband modes.
2. A square pulse is the best fastest unselective family for both sideband modes.
3. Once the matched local transmon-coherence reference is included, no family continues to satisfy the original selective thresholds, and only the storage fast-square pulse remains threshold-valid.
4. The simultaneous two-tone extension shows that the single-photon `|g,0,1> -> |g,1,0>` transfer works nearly perfectly in the closed system through a resonant bright-state mechanism, with about `29.5 ns` transfer time at equal `12 MHz` leg couplings.
5. A detuned Raman-like two-tone drive lowers the `|f>` occupancy to about `0.12`, but stretches the transfer to about `348 ns`, where readout decay reduces the noisy peak readout occupancy to about `0.56`.
6. The same constant two-tone drive does not stay confined to the intended single-transfer ladder for `n > 1`, so the clean near-unit transfer result is specific to the single-photon case.

The selected-case variables at the top of the notebook let you jump directly to one manifold and one winner class without rerunning the full study."""
        ),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.12",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    NOTEBOOK_PATH.write_text(json.dumps(build_notebook(), indent=2), encoding="utf-8")
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
